### ISSUE TITLE
Can we execute the repo over any cloud platform.

### ISSUE THREAD

**Issue by himanshu112** [cchen156/Learning-to-See-in-the-Dark#50]

**Comment by himanshu112** [comment]
**I am facing the following problem when tried to import test_Sony using google colab**--
ValueError                                Traceback (most recent call last)
<ipython-input-16-85231e8510cb> in <module>()
----> 1 import test_Sony

/content/Learning-to-See-in-the-Dark/test_Sony.py in <module>()
    100 in_image = tf.placeholder(tf.float32, [None, None, None, 4])
    101 gt_image = tf.placeholder(tf.float32, [None, None, None, 3])
--> 102 out_image = network(in_image)
    103 
    104 saver = tf.train.Saver()

/content/Learning-to-See-in-the-Dark/test_Sony.py in network(input)
     40 
     41 def network(input):
---> 42     conv1 = slim.conv2d(input, 32, [3, 3], rate=1, activation_fn=lrelu, scope='g_conv1_1')
     43     conv1 = slim.conv2d(conv1, 32, [3, 3], rate=1, activation_fn=lrelu, scope='g_conv1_2')
     44     pool1 = slim.max_pool2d(conv1, [2, 2], padding='SAME')

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py in func_with_args(*args, **kwargs)
    181       current_args = current_scope[key_func].copy()
    182       current_args.update(kwargs)
--> 183     return func(*args, **current_args)
    184 
    185   _add_op(func)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/layers.py in convolution2d(inputs, num_outputs, kernel_size, stride, padding, data_format, rate, activation_fn, normalizer_fn, normalizer_params, weights_initializer, weights_regularizer, biases_initializer, biases_regularizer, reuse, variables_collections, outputs_collections, trainable, scope)
   1152                      trainable,
   1153                      scope,
-> 1154                      conv_dims=2)
   1155 
   1156 convolution2d.__doc__ = convolution.__doc__

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py in func_with_args(*args, **kwargs)
    181       current_args = current_scope[key_func].copy()
    182       current_args.update(kwargs)
--> 183     return func(*args, **current_args)
    184 
    185   _add_op(func)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/layers.py in convolution(inputs, num_outputs, kernel_size, stride, padding, data_format, rate, activation_fn, normalizer_fn, normalizer_params, weights_initializer, weights_regularizer, biases_initializer, biases_regularizer, reuse, variables_collections, outputs_collections, trainable, scope, conv_dims)
   1055         _scope=sc,
   1056         _reuse=reuse)
-> 1057     outputs = layer.apply(inputs)
   1058 
   1059     # Add variables to collections.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in apply(self, inputs, *args, **kwargs)
    803       Output tensor(s).
    804     """
--> 805     return self.__call__(inputs, *args, **kwargs)
    806 
    807   def _set_learning_phase_metadata(self, inputs, outputs):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py in __call__(self, inputs, *args, **kwargs)
    360 
    361       # Actually call layer
--> 362       outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
    363 
    364     if not context.executing_eagerly():

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    726         if all(hasattr(x, 'shape') for x in input_list):
    727           input_shapes = nest.map_structure(lambda x: x.shape, inputs)
--> 728         self.build(input_shapes)
    729         self.built = True
    730 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/convolutional.py in build(self, input_shape)
    159         constraint=self.kernel_constraint,
    160         trainable=True,
--> 161         dtype=self.dtype)
    162     if self.use_bias:
    163       self.bias = self.add_weight(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py in add_weight(self, name, shape, dtype, initializer, regularizer, trainable, constraint, use_resource, synchronization, aggregation, partitioner)
    274             synchronization=synchronization,
    275             aggregation=aggregation,
--> 276             getter=vs.get_variable)
    277 
    278         if regularizer:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in add_weight(self, name, shape, dtype, initializer, regularizer, trainable, constraint, partitioner, use_resource, synchronization, aggregation, getter)
    563         use_resource=use_resource,
    564         synchronization=synchronization,
--> 565         aggregation=aggregation)
    566 
    567     if regularizer is not None:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpointable/base.py in _add_variable_with_custom_getter(self, name, shape, dtype, initializer, getter, overwrite, **kwargs_for_getter)
    533     new_variable = getter(
    534         name=name, shape=shape, dtype=dtype, initializer=initializer,
--> 535         **kwargs_for_getter)
    536 
    537     # If we set an initializer and the variable processed it, tracking will not

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint, synchronization, aggregation)
   1465       constraint=constraint,
   1466       synchronization=synchronization,
-> 1467       aggregation=aggregation)
   1468 
   1469 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint, synchronization, aggregation)
   1215           constraint=constraint,
   1216           synchronization=synchronization,
-> 1217           aggregation=aggregation)
   1218 
   1219   def _get_partitioned_variable(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint, synchronization, aggregation)
    508       if "constraint" in function_utils.fn_args(custom_getter):
    509         custom_getter_kwargs["constraint"] = constraint
--> 510       return custom_getter(**custom_getter_kwargs)
    511     else:
    512       return _true_getter(

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/layers.py in layer_variable_getter(getter, *args, **kwargs)
   1742   def layer_variable_getter(getter, *args, **kwargs):
   1743     kwargs['rename'] = rename
-> 1744     return _model_variable_getter(getter, *args, **kwargs)
   1745 
   1746   return layer_variable_getter

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/layers.py in _model_variable_getter(getter, name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, rename, use_resource, **_)
   1733       partitioner=partitioner,
   1734       custom_getter=getter,
-> 1735       use_resource=use_resource)
   1736 
   1737 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py in func_with_args(*args, **kwargs)
    181       current_args = current_scope[key_func].copy()
    182       current_args.update(kwargs)
--> 183     return func(*args, **current_args)
    184 
    185   _add_op(func)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/variables.py in model_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, device, partitioner, custom_getter, use_resource)
    295                  caching_device=caching_device, device=device,
    296                  partitioner=partitioner, custom_getter=custom_getter,
--> 297                  use_resource=use_resource)
    298   return var
    299 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py in func_with_args(*args, **kwargs)
    181       current_args = current_scope[key_func].copy()
    182       current_args.update(kwargs)
--> 183     return func(*args, **current_args)
    184 
    185   _add_op(func)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/variables.py in variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, device, partitioner, custom_getter, use_resource)
    250                   caching_device=caching_device,
    251                   partitioner=partitioner,
--> 252                   use_resource=use_resource)
    253 
    254 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, constraint, synchronization, aggregation)
    479           constraint=constraint,
    480           synchronization=synchronization,
--> 481           aggregation=aggregation)
    482 
    483     # Set trainable value based on synchronization value.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint, synchronization, aggregation)
    846                          "reuse=tf.AUTO_REUSE in VarScope? "
    847                          "Originally defined at:\n\n%s" % (
--> 848                              name, "".join(traceback.format_list(tb))))
    849       found_var = self._vars[name]
    850       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable g_conv1_1/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 252, in variable
    use_resource=use_resource)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 297, in model_variable
    use_resource=use_resource)

**Comment by nthacks** [comment]
Required python (version 2.7) libraries: Tensorflow (>=1.1) + Scipy + Numpy + Rawpy.

You seem to be using python3.6

**Comment by umitbulut** [comment]
Since google colab is basically running a virtual machine, you need to extra pay attention to the root folders and files. I've tried and it's really a painful thing to work on.

**Comment by willswordh** [comment]
> Required python (version 2.7) libraries: Tensorflow (>=1.1) + Scipy + Numpy + Rawpy.
> 
> You seem to be using python3.6

@nthacks I actually are using python version 3.10 and it works with all the libraries. Not sure why 3.6 is not working that the OP had.
